### ISSUE TITLE
Sorry! Maybe there is something wrong with your Singleton code.

### ISSUE THREAD

**Issue by ghost** [JakubVojvoda/design-patterns-cpp#3]
When I modified your main function as below, I found that the code could run normally.

int main()
{
  Singleton::get()->tell();
  Singleton::restart();
  
  Singleton obj = *(Singleton::get());
  obj.tell();
  return 0;
}

I could create a Singleton object outside the Singleton class.

**Comment by JakubVojvoda** [comment]
You are absolutely right. I deleted copy constructor and assignment operator of the Singleton class, and it should be working correctly now. Thanks for finding this bug.
